config/routes.rb
DeweyDecibelDatabase::Application.routes.draw do
  
  get "delete_song_conf/deleteConfirm"
  get "add_page/addSingleSong"
  get "add_page/addListSongs"
  get "add_page/save"
  get "add_page/addAlbum"
  get "admin_inspect/admin_insepect"
  get "album_inspect/albumInspect"
  get "album_inspect/songInspect"
  get "album_inspect/singleSongInspect"
  get "album_inspect/artistInspect"
  root  'home_page#home'
  match '/admin',              to: "admin_page#admin",                  via: 'get'
  match '/search',             to: "search_box#search",                 via: 'get'
  match '/add',                to: "add_box#addModal",                  via: 'get'
  match '/songInspect',        to: "song_inspect#songInspect",          via: 'get'
  match '/adminInspect',       to: "admin_inspect#adminInspect",        via: 'get'
  match '/adminInspectUp',     to: "admin_inspect#updatePrivilege",     via: 'get'
  match '/deleteConfirm',      to: "delete_user_conf#deleteConfirm",    via: 'get'
  match '/deletePlaylist',     to: "delete_playlist_conf#deleteConfirm",via: 'get'
  match '/showPlaylist',        to: "playlists#showBox",                 via: 'get'
  match '/songs',             to: "songs#index",                        via: 'get'
  match '/addUser',             to: "add_user#addNewUser",              via: 'get'
  match '/newPrivileges',       to: "add_user#addNewPrivileges",        via: 'get'
  
  match '/auth/:provider/callback' => 'sessions#create', :via => [:get, :post]
  match '/signout' => 'sessions#destroy', :as => :signout, :via => [:get, :post]
  match '/signin' => 'sessions#new', :as => :signin, :via => [:get, :post]

  match '/remove_song_from_playlist', to: "playlist_page#remove_song",  via: 'delete'
  
  resources :playlists

  resources :songs 

  resources :users

  resources :privileges

end

app/models/song.rb
class Song < ActiveRecord::Base
  has_and_belongs_to_many :playlists, :join_table => "playlists_songs"
  validates :title, :artist, :album, :duration, presence: true

  # songs table query used in playlist view
  def self.tokens(query)

  	# make the query on title field
    songs = where("title like ?", "%#{query}%")
    ## option to add new song if not found -- excluded
    # if songs.empty?
    # [{id: "<<<#{query}>>>", title: "New: \"#{query}\""}]
    
    ## return results
      songs
    #end
  end
  
  # used for getting ids of tokens in text area
  def self.ids_from_tokens(tokens)
    ## used for creating a new song if search is empty -- excluded
    tokens.gsub!(/<<<(.+?)>>>/) { create!(title: $1).id }
    tokens.split(',')
  end


  def fccClean
    self.fccFlag
  end

  def duration_str
    Song.get_time_str(duration)
  end

  def self.get_time_str (some_time)
    Time.at(some_time.to_i).utc.strftime('%H:%M:%S')
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all

    respond_to do |format|
      format.html {
        @songs = Song.order(:title)
      }
      # json for all songs specified by query param q
      format.json { 
        render json: @songs.tokens(params[:q]) 
      }
    end
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render action: 'show', status: :created, location: @song }
      else
        format.html { render action: 'new' }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1protect_from_forgery :except => [:update, :delete, :create]
  # PATCH/PUT /songs/1.json
  def update
      #@song = song.find(params[:id])
      if @song.update_attributes(song_params)
        flash[:success] = "Song updated"
        redirect_to @song
      else
        render 'edit'
      end
    end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:title, :artist, :album, :duration, :quality, :fccFlag, :is_qDrive, :location, :format, :review, :playlists)
    end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </div>
  <div class="field">
    <%= f.label :album %><br>
    <%= f.text_field :album %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.time_select :duration %>
  </div>
  <div class="field">
    <%= f.label :quality %><br>
    <%= f.number_field :quality %>
  </div>
  <div class="field">
    <%= f.label :fccFlag %><br>
    <%= f.check_box :fccFlag %>
  </div>
  <div class="field">
    <%= f.label :is_qDrive %><br>
    <%= f.check_box :is_qDrive %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :format %><br>
    <%= f.text_field :format %>
  </div>
  <div class="field">
    <%= f.label :review %><br>
    <%= f.text_area :review %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<script>
	$(document).ready(function() {
		parent.$.colorbox.resize({width:"82%", height:"75%"});
	});

</script>

<search>
  <div class="iframe">
  <table class="table table-striped table-border table-hover" id="myTable">
      <thead>
        <tr>
        <th><strong>Title</strong></th>
        <th><strong>Artist</strong></th>
        <th><strong>Album</strong></th>
        <th><strong>Inspect</strong></th>
        <th><strong>Remove</strong></th>
        </tr>
      </thead>
    <tbody>
          <% @songs.each do |song| %>
         <tr>
            <td><%= song.title %></td>
            <td><%= song.artist %></td>
            <td><%= song.album %></td>
            <td>
              <%= link_to '<button type="button" class="btn btn-info">Info</button>'.html_safe, :controller => "song_inspect", :action => "songInspect", :song => song.id  %>
            </td>
            <td>
              <%= link_to '<button type="button" class="btn btn-danger">Delete</button>'.html_safe, :controller => "delete_song_conf", :action => "deleteConfirm", :song => song.id  %>
            </td>
         </tr>
        <% end %>
    </tbody>
  </table>
  <!-- </body> -->
  <script type="text/javascript">
    function getURLParameter(name) {
        return decodeURI(
            (RegExp(name + '=' + '(.+?)(&|$)').exec(location.search)||[,null])[1]
        );
    }

    $(document).ready(function(){
        var searchParam = getURLParameter('keyword');
        var filter;
        if(searchParam != "null")
        {
          filter = searchParam;
        }
        else {
          filter = "";
        }

        var table = $('#myTable').dataTable({
          "sPaginationType": "bootstrap"
        });

        table.fnFilter( filter );
       
    });

  </script>
  </div>
</search>

app/views/songs/new.html.erb
<h1>New song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @song.title %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @song.artist %>
</p>

<p>
  <strong>Album:</strong>
  <%= @song.album %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @song.duration %>
</p>

<p>
  <strong>Quality:</strong>
  <%= @song.quality %>
</p>

<p>
  <strong>Fccclean:</strong>
  <%= @song.fccClean %>
</p>

<p>
  <strong>Is qdrive:</strong>
  <%= @song.is_qDrive %>
</p>

<p>
  <strong>Location:</strong>
  <%= @song.location %>
</p>

<p>
  <strong>Format:</strong>
  <%= @song.format %>
</p>

<p>
  <strong>Review:</strong>
  <%= @song.review %>
</p>

<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>