config/routes.rb
DeweyDecibelDatabase::Application.routes.draw do
  
  get "delete_song_conf/deleteConfirm"
  get "add_page/addSingleSong"
  get "add_page/addListSongs"
  get "add_page/save"
  get "add_page/addAlbum"
  get "admin_inspect/admin_insepect"
  get "album_inspect/albumInspect"
  get "album_inspect/songInspect"
  get "album_inspect/singleSongInspect"
  get "album_inspect/artistInspect"
  root  'home_page#home'
  match '/admin',              to: "admin_page#admin",                  via: 'get'
  match '/search',             to: "search_box#search",                 via: 'get'
  match '/add',                to: "add_box#addModal",                  via: 'get'
  match '/songInspect',        to: "song_inspect#songInspect",          via: 'get'
  match '/adminInspect',       to: "admin_inspect#adminInspect",        via: 'get'
  match '/adminInspectUp',     to: "admin_inspect#updatePrivilege",     via: 'get'
  match '/deleteConfirm',      to: "delete_user_conf#deleteConfirm",    via: 'get'
  match '/deletePlaylist',     to: "delete_playlist_conf#deleteConfirm",via: 'get'
  match '/showPlaylist',        to: "playlists#showBox",                 via: 'get'
  match '/songs',             to: "songs#index",                        via: 'get'
  match '/addUser',             to: "add_user#addNewUser",              via: 'get'
  match '/newPrivileges',       to: "add_user#addNewPrivileges",        via: 'get'
  
  match '/auth/:provider/callback' => 'sessions#create', :via => [:get, :post]
  match '/signout' => 'sessions#destroy', :as => :signout, :via => [:get, :post]
  match '/signin' => 'sessions#new', :as => :signin, :via => [:get, :post]

  match '/remove_song_from_playlist', to: "playlist_page#remove_song",  via: 'delete'
  
  resources :playlists

  resources :songs 

  resources :users

  resources :privileges

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
	has_and_belongs_to_many :songs, :join_table => "playlists_songs"
	belongs_to :user

  #list in most-recent-first order (rev. chron.)
  #default_scope -> { order('created as DESC') }

	# getter for adding songs to playlist
	attr_reader :song_tokens

  # setter for adding songs to playlist
  def song_tokens=(tokens)
    self.song_ids = Song.ids_from_tokens(tokens)
  end

  def contains_explicit?
    self.songs.exists?(fccFlag: false)
  end

  def user=(user)
    self.user = user
  end

  def get_duration
    sum = 0

    songs.each do |song|
      sum += song.duration.to_i
    end

    Song.get_time_str(sum)

  end

end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: [:show, :edit, :update, :destroy]

  # GET /playlists
  # GET /playlists.json
  def index
    @playlists = Playlist.all
  end

  # GET /playlists/1
  # GET /playlists/1.json
  def show
  end

  # GET /playlists/new
  def new
      @playlist = Playlist.new
    
      @songs = Song.order(:artist)

      respond_to do |format|
      format.html
      # json for all songs specified by query param q
      format.json { render json: @songs.tokens(params[:q]) }
      end
  end

  # GET /playlists/1/edit
  def edit
  end

  # POST /playlists
  # POST /playlists.json
  def create
    
    @playlist = Playlist.new(playlist_params)

    respond_to do |format|
      if @playlist.save
        format.html { redirect_to playlists_path, notice: 'Playlist was successfully created.' }
        format.json { render action: 'show', status: :created, location: @playlist }
      else
        format.html { render action: 'new' }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end
  
  
  def showBox
        @playlistID = params[:playlistID]
        
        @playlist = Playlist.find(@playlistID)
  end
  

  # PATCH/PUT /playlists/1
  # PATCH/PUT /playlists/1.json
  def update
    
    #@songs = Song.order(:artist)
    @playlist = Playlist.find(params[:id])
    
    respond_to do |format|
      if @playlist.update(playlist_params)
        format.html { redirect_to playlists_path, notice: 'Playlist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1
  # DELETE /playlists/1.json
  def destroy
    @playlist.destroy
    respond_to do |format|
      format.html { redirect_to playlists_path }
      format.json { head :no_content }
    end
  end


  def remove_song
    #@playlist.find(params[:
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playlist
      @playlist = Playlist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def playlist_params
      params.require(:playlist).permit(:users, :title, :qDrive, :notes, :song_tokens, :user_id)
      # EDITED FROM user_id
    end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/_form.html.erb
<style>
  ul.token-input-list-facebook
  {
    margin: 20px auto;
    border: 1px solid #999;
    /*width: 50%;*/
    /*height: 70%;*/
  }

  #submit_button
  {
    margin: 0 auto;
    position: absolute;
    left: 45%;
    /*clear: both;*/
  }

</style>



<%= form_for(@playlist) do |f| %>
  <% if @playlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@playlist.errors.count, "error") %> prohibited this playlist from being saved:</h2>

      <ul>
      <% @playlist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :users %><br>
    <%= f.collection_select :user_id, User.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :song_tokens, "Songs" %><br>
    <%= f.text_field :song_tokens, data: {load: @playlist.songs} %>
  </div>
  <div class="field">
    <%= f.label :qDrive %><br>
    <%= f.check_box :qDrive %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes, :style => 'width: 50%;' %>
  </div>
  <div class="actions" style="margin: 0 auto;">
    <%= f.submit :class => 'btn btn-success', :id => 'submit_button' %>
  </div>
<% end %>

app/views/playlists/_singleton.html.erb
<script>
function delLightbox(playlistID){    
  var url1 = "/deletePlaylist?playlistID=";
  
  var start = url1.concat(playlistID);

  console.log(start);
  $.colorbox({width:"80%", height:"80%", iframe:true, href:start});
}

function showLightbox(playlistID){    
  var url1 = "/showPlaylist?playlistID=";
  
  var start = url1.concat(playlistID);

  console.log(start);
  $.colorbox({width:"80%", height:"80%", iframe:true, href:start});
}
</script>

<div class="list-group-item playlist_singleton">
  <%# TODO REMOVE, PLAYLIST POPULATE, PLAYLIST TITLE, PLAYLIST FCC FLAG %>
  <div class="row">
    <div class="col-md-6">
      <h4><%= playlist.title %></h4>
      <p>Duration: <%= playlist.get_duration %></p>
      <p>
        Clean?
        <% if playlist.contains_explicit? %>
          <span style="color:red">NO</span>
        <% else %>
          <span style="color:green">YES</span>
        <% end %>
      </p>
      <p>
        Q-drive?
        <% if playlist.qDrive %>
          <span style="color:orange">YES</span>
        <% else %>
          <span style="color:blue">NO</span>
        <% end %>
      </p>
      <p>
        <%= playlist.notes %>
      </p>
    </div>
    <div class="col-md-6">
      <%= link_to '<button type="button" class="btn btn-info" style="font-family:Verdana, sans-serif;">Edit Playlist</button>'.html_safe,
       edit_playlist_path(playlist) %>
       
       <button class="btn" style="float:center; font-family:Verdana, sans-serif; background-color:#B452CD; color:white;" onClick="showLightbox(<%= playlist.id %>)">Show Playlist</button>
       
       <button type="button" class="btn btn-danger" style="float:right; font-family:Verdana, sans-serif;" onClick="delLightbox(<%= playlist.id %>)">Delete Playlist</button>
       
    </div>
  </div>
  <table class="table table-striped table-border table-hover">
    <thead>
      <tr>
        <th><strong>Song</strong></th>
        <th><strong>Artist</strong></th>
        <th><strong>Album</strong></th>
        <th><strong>Inspect</strong></th>
        <th><strong>Remove</strong></th>
      </tr>
    </thead>
    <tbody>
    <% playlist.songs.each do |song| %>
    <tr>
      <td><%= song.title %></td>
      <td><%= song.artist %></td>
      <td><%= song.album %></td>
      <td>
        <%= link_to '<button type="button" class="btn btn-info">Info</button>'.html_safe, {:controller => "song_inspect", :action => "songInspect", :song => song.id } %>
      </td>
      <td>
        <%= button_to 'Remove', remove_song_from_playlist_path({ playlist_id: playlist.id, song_id: song.id }) , method: :delete, :class => 'btn btn-warning' %>
      </td>
    </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/playlists/edit.html.erb
<div id="all_content"> 
  <div id="yield_wrapper">
    <%= render partial: 'layouts/header' %>
    <%= render partial: 'layouts/notify' %>

    <h1>Edit playlist</h1>

    <%= render 'form' %>
  
    <%= link_to '<button type="button" class="btn btn-warning">Back</button>'.html_safe, playlists_path %>
  </div
</div>

<%= render partial: 'layouts/footer' %>

app/views/playlists/index.html.erb
<div id="all_content">
  <div id="yield_wrapper">
    <%= render :partial => 'layouts/header' %>
    <%= render :partial => 'layouts/notify' %>

    <h1 id="playlist_owner"><%= User.first.name %>'s Playlists</h1>
  
    
    <div class="container">

    <%= button_to 'New Playlist', new_playlist_path,
     :class => 'btn btn-success', :id => 'plist_new_btn', :method => 'get'  %> 
      <div class="list-group">
        <% @playlists.each do |playlist| %>
          <%= render partial: 'playlists/singleton', locals: { playlist: playlist} %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= render :partial => 'layouts/footer' %>

app/views/playlists/new.html.erb
<div id="all_content">
  <div id="yield_wrapper">
    <%= render :partial => 'layouts/header' %>
    <%= render :partial => 'layouts/notify' %>

    <h1 id="playlist_owner">New playlist</h1>
    
    <div class="container" style="margin: 0 auto;">
        <%= render 'form' %>
    </div>

    <%= link_to 'Back', playlists_path, :class => 'btn btn-warning' %>
  </div>
</div>

<%= render :partial => 'layouts/footer' %>

app/views/playlists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Users:</strong>
  <%= @playlist.user %>
  <% # EDITED FROM user_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @playlist.title %>
</p>

<p>
  <strong>Songs:</strong>
  <ul>
  <% @playlist.songs.each do |song| %>
    <li><%= song.title %></li>
  <% end %>
  </ul>

</p>

<p>
  <strong>Qdrive:</strong>
  <%= @playlist.qDrive %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @playlist.notes %>
</p>

<%= link_to 'Edit', edit_playlist_path(@playlist) %> |
<%= link_to 'Back', playlists_path %>






<div id="all_content"> 
  <div id="yield_wrapper">
    <%= render partial: 'layouts/header' %>
    <%= render partial: 'layouts/notify' %>

    <h1>Edit playlist</h1>

    <%= render 'form' %>
  
  	<%= link_to '<button type="button" class="btn btn-info">Edit</button>'.html_safe, edit_playlist_path(@playlist) %> |
    <%= link_to '<button type="button" class="btn btn-warning">Back</button>'.html_safe, playlists_path %>
  </div
</div>

<%= render partial: 'layouts/footer' %>

app/views/playlists/showBox.html.erb
<script>
	
$(document).ready(function () {
	$('#plink').click(function(){
		parent.$.colorbox.close();
		window.parent.location.href='/playlists';
	}
);
});
	
</script>



<search>
	<div class="iframe">
		<p>
			<div class="col-md-2"></div>
			<div class="col-md-8">
  				<h1><center>
  					<strong><%= @playlist.title %></strong>
  				</center></h1>
  			</div>
  			<div class="col-md-2">
  				<%= link_to '<button type="button" id="plink" class="btn btn-success">Go To My Playlists</button>'.html_safe %>
 			</div>
		</p>
	<!-- <body> -->
	<table class="table table-striped table-border table-hover" id="myTable">
  		<thead>
  			<tr>
  			<th><strong>Song</strong></th>
  			<th><strong>Artist</strong></th>
  			<th><strong>Album</strong></th>
  			<th><strong>Inspect</strong></th>
  			</tr>
  		</thead>
		<tbody>
        	<% @playlist.songs.each do |song| %>
     		 <tr>
       			<td><%= song.title %></td>
       			<td><%= song.artist %></td>
       			<td><%= song.album %></td>
       			<td>
       				<%= link_to '<button type="button" class="btn btn-info">Info</button>'.html_safe, :controller => "song_inspect", :action => "songInspect", :song => song.id  %>

       			</td>
     		 </tr>
   			<% end %>
		</tbody>
	</table>
	<!-- </body> -->
	<div class="col-md-6">
		<table class="table table-striped table-bordered table-hover table-nonfluid">
				<tbody>
					<tr>
						<td><strong>Q-Drive?</strong></td>
						<td><div class="btn-group" data-toggle="buttons">
							<% if @playlist.qDrive %>
  								<span style="color:orange">YES</span>
  							<% else%>
  								<span style="color:blue">NO</span>
  							<% end %>
  							</div>
  						</td>
					</tr>
					<tr>
						<td><strong>Clean</strong></td>
						<td><div class="btn-group" data-toggle="buttons">
							<% if @playlist.contains_explicit? %>
          						<span style="color:red">NO</span>
        					<% else %>
          						<span style="color:green">YES</span>
        					<% end %>
  							</div>
  						</td>
					</tr>  			
					<tr>
						<td><strong>Duration</strong></td>
						<td><div class="btn-group" data-toggle="buttons">
							<%= @playlist.get_duration %>
  							</div>
  						</td>
					</tr>  			
					<tr> 			
				</tbody>
			</table>
		<!-- </body> -->
	</div>
	<div class="col-md-6">
		<table class="table table-striped table-border table-hover" id="myTable">
  		<thead>
  			<tr>
  			<th><strong><center>Notes</center></strong></th>
  			</tr>
  		</thead>
		<tbody>
     		 <tr>
       			<td><%= @playlist.notes %></td>
     		 </tr>
		</tbody>
	</table>
	</div>
	</div>
  <script type="text/javascript">
    $(document).ready(function(){
        $('#myTable').dataTable({
          "sPaginationType": "bootstrap"
        });
    });
  </script>
</search>